### ISSUE TITLE
badge triggers

### ISSUE THREAD

**Issue by olivia-y-chen** [joshisacow/pikadle#47]
actually put our badge triggers in the userbase
triggers for number of pokemon (1, 5, 10, 20, 30, 50, 75, 100, 1017)
triggers for high score on safari (1, 5, 10, 20, 25, 30)
OPTIONAL:  catching legendary pokemon? catching a specific pokemon? getting a pokemon in 1 attempt?

**Comment by Will-Yun** [comment]
The badges for normal pokemon catching work.

**Comment by Will-Yun** [comment]
badge triggers for safari score are in place

**Comment by Will-Yun** [comment]
triggers are done
