### ISSUE TITLE
badge sprites + badge acquire dates

### ISSUE THREAD

**Issue by olivia-y-chen** [joshisacow/pikadle#49]
get sprites for each badge
no api exists for badges so you will have to download badge sprites for each badge in our table and import them into assets. load these assets into imgs blah blah blah google it.
https://bulbapedia.bulbagarden.net/wiki/Badge
^ has all badges in pokemon w/ transparent backgrounds. get badges from there

**Comment by joshisacow** [comment]
also want to add when we acquired the badge to db

Alternative to olly suggestion of downloading each image, we can store each image in our db potentially and retrieve when we call our fetch api. Along the same vein, would also add the date acquired column into db

**Comment by olivia-y-chen** [comment]
we are actually j gonna save the image address to our table under a new column sprites for our badge table
